// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU1aV7v12IVpnyP39R-4jmT774viAC0ro',
    appId: '1:664408035542:web:649fd8b24d33501dc2b977',
    messagingSenderId: '664408035542',
    projectId: 'college_project-project-a8d33',
    authDomain: 'college_project-project-a8d33.firebaseapp.com',
    databaseURL: 'https://college_project-project-a8d33-default-rtdb.firebaseio.com',
    storageBucket: 'college_project-project-a8d33.firebasestorage.app',
    measurementId: 'G-F32Y2W6XR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNI8ab253CdubWSsmmFXL-IcH3w0I0NzI',
    appId: '1:664408035542:android:b22c5fee2112869ac2b977',
    messagingSenderId: '664408035542',
    projectId: 'college_project-project-a8d33',
    databaseURL: 'https://college_project-project-a8d33-default-rtdb.firebaseio.com',
    storageBucket: 'college_project-project-a8d33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjZpXhtV9aLtT44Al-s5cbCi3-mEoZgEM',
    appId: '1:664408035542:ios:c4eecddc9c8c99a8c2b977',
    messagingSenderId: '664408035542',
    projectId: 'college_project-project-a8d33',
    databaseURL: 'https://college_project-project-a8d33-default-rtdb.firebaseio.com',
    storageBucket: 'college_project-project-a8d33.firebasestorage.app',
    iosClientId: '664408035542-euvjauevdje59eduimtf8j69r1jle604.apps.googleusercontent.com',
    iosBundleId: 'com.example.college_projectProject',
  );
}
